services:
  - type: web
    name: clinic-saas-mvp
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader wordnet omw-1.4
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
